version: 2.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    dotnet build EdgeAuthToken.sln --configuration Release
test_script:
- cmd: >-
    dotnet test EdgeAuthToken.Tests\EdgeAuthToken.Tests.csproj --logger:Appveyor
artifacts:
- path: '**\bin\Release\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: fmO7kQHZTLHCEhMMLzxqfjHrwqeTJAtXLoe4NOQCGY5+oQMM13sB5l7LeCOWJml6
  on:
    branch: master